import React, { useEffect, useMemo, useState } from "react";
import { formatThaiDate, requireSupabase, rpc } from "../../core.js";
import { Badge, CardTitle, Empty, ErrorState, Loading } from "../components/UI.jsx";

function monthStart(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-01`}
function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d}
function BarList({rows,nameKey="label",valueKey="value",suffix=""}){if(!rows?.length)return <Empty title="ยังไม่มีข้อมูลสำหรับกราฟ" text="ลองเปลี่ยนตัวกรองหรือเลือกเดือนที่มีประวัติงาน"/>;const max=Math.max(1,...rows.map(r=>num(r[valueKey])));return <div className="bar-list">{rows.map((r,i)=><div className="bar-row" key={`${r[nameKey]}-${i}`}><div className="bar-name" title={r[nameKey]}>{r[nameKey]||"ไม่ระบุ"}</div><div className="bar-track"><div className="bar-fill" style={{width:`${Math.max(3,num(r[valueKey])/max*100)}%`}}/></div><div className="bar-value">{num(r[valueKey]).toLocaleString("th-TH")}{suffix}</div></div>)}</div>}

export default function KPIModule(){
  const [departments,setDepartments]=useState([]),[machines,setMachines]=useState([]),[filters,setFilters]=useState({department_id:"",machine_id:"",month:monthStart()}),[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  async function loadMasters(){const sb=requireSupabase();const [d,m]=await Promise.all([sb.from("departments").select("id,dept_code,dept_name,is_active").eq("is_active",true).order("sort_order"),sb.from("machines").select("id,department_id,machine_no,machine_name,is_active").eq("is_active",true).order("machine_name")]);if(d.error)throw d.error;if(m.error)throw m.error;setDepartments(d.data||[]);setMachines(m.data||[])}
  async function load(){setLoading(true);setError("");try{await loadMasters();const args={p_department_id:filters.department_id||null,p_machine_id:filters.machine_id||null,p_month:filters.month};const [summary,pareto,causes,topMachines]=await Promise.all([rpc("kpi_summary",args),rpc("kpi_problem_pareto",args),rpc("kpi_top_causes",args),rpc("kpi_top_machines",{p_department_id:args.p_department_id,p_month:args.p_month})]);const sb=requireSupabase();const month=filters.month.slice(0,7),start=`${month}-01`,end=new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5,7)),0,12)).toISOString().slice(0,10);let q=sb.from("pm_schedule").select("id,due_date,plan_title_snapshot,machine_no_snapshot,machine_name_snapshot,overall_result,completed_at").eq("status","completed").gte("due_date",start).lte("due_date",end).order("due_date",{ascending:false}).limit(80);if(filters.department_id)q=q.eq("department_id",filters.department_id);if(filters.machine_id)q=q.eq("machine_id",filters.machine_id);const {data:pmHistory,error:pmErr}=await q;if(pmErr)throw pmErr;setData({summary:summary?.[0]||summary||{},pareto:pareto||[],causes:causes||[],topMachines:topMachines||[],pmHistory:pmHistory||[]})}catch(e){setError(e.message||"โหลด KPI ไม่สำเร็จ")}finally{setLoading(false)}}
  useEffect(()=>{load()},[filters.department_id,filters.machine_id,filters.month]);
  async function updatePmResult(id,value){try{const sb=requireSupabase();const {error}=await sb.from("pm_schedule").update({overall_result:value||null}).eq("id",id);if(error)throw error;await load()}catch(e){setError(e.message||"อัปเดตผล PM ไม่สำเร็จ")}}
  const filteredMachines=useMemo(()=>machines.filter(m=>!filters.department_id||m.department_id===filters.department_id),[machines,filters.department_id]);
  if(loading&&!data)return <Loading/>;if(error&&!data)return <ErrorState message={error} onRetry={load}/>;
  const s=data?.summary||{};
  return <div className="stack"><section className="hero"><div className="hero-kicker">MAINTENANCE PERFORMANCE</div><h1>KPI และรายงาน</h1><p>Downtime, Breakdown, MTBF, MTTR, Availability และ Pareto จากข้อมูล Repair จริง</p></section>
    <div className="card flat"><CardTitle icon="filter" title="ตัวกรอง KPI" sub="กรองตามแผนก เครื่องจักร และเดือน"/><div className="field-grid cols-3"><div className="field"><label>แผนก</label><select className="select" value={filters.department_id} onChange={e=>setFilters(f=>({...f,department_id:e.target.value,machine_id:""}))}><option value="">ทุกแผนก</option>{departments.map(d=><option key={d.id} value={d.id}>{d.dept_code} · {d.dept_name}</option>)}</select></div><div className="field"><label>เครื่องจักร</label><select className="select" value={filters.machine_id} onChange={e=>setFilters(f=>({...f,machine_id:e.target.value}))}><option value="">ทุกเครื่อง</option>{filteredMachines.map(m=><option key={m.id} value={m.id}>{m.machine_no} · {m.machine_name}</option>)}</select></div><div className="field"><label>เดือน</label><input className="input" type="month" value={filters.month.slice(0,7)} onChange={e=>setFilters(f=>({...f,month:`${e.target.value}-01`}))}/></div></div></div>
    {loading&&<div className="card flat"><Loading text="กำลังคำนวณ KPI…"/></div>}
    {error&&<div className="card flat" style={{color:"#B82E42"}}>{error}</div>}
    <div className="kpi-grid"><div className="kpi-card danger"><div className="kpi-label">Downtime</div><div className="kpi-value">{num(s.downtime_min).toLocaleString("th-TH")}</div><div className="kpi-sub">นาที</div></div><div className="kpi-card warn"><div className="kpi-label">จำนวนครั้งเสีย</div><div className="kpi-value">{num(s.breakdown_count)}</div><div className="kpi-sub">ครั้ง</div></div><div className="kpi-card"><div className="kpi-label">MTTR</div><div className="kpi-value">{num(s.mttr_min).toFixed(1)}</div><div className="kpi-sub">นาที/ครั้ง</div></div><div className="kpi-card purple"><div className="kpi-label">MTBF</div><div className="kpi-value">{num(s.mtbf_hour).toFixed(1)}</div><div className="kpi-sub">ชั่วโมง</div></div><div className="kpi-card good"><div className="kpi-label">Availability</div><div className="kpi-value">{num(s.availability_pct).toFixed(2)}%</div><div className="kpi-sub">อิง 24 ชั่วโมง/วัน</div></div></div>
    <div className="grid grid-3"><div className="card"><CardTitle icon="kpi" title="Pareto ปัญหาซ้ำ" sub="เรียงตามจำนวนครั้งเกิด"/><BarList rows={(data?.pareto||[]).map(x=>({label:x.problem_name,value:x.times_occurred}))}/></div><div className="card"><CardTitle icon="alert" title="สาเหตุเสียสูงสุด" sub="เรียงตาม Loss Time"/><BarList rows={(data?.causes||[]).map(x=>({label:x.cause_name,value:x.downtime_min}))} suffix="m"/></div><div className="card"><CardTitle icon="machine" title="เครื่อง Loss Time สูง" sub="เครื่องที่ควรให้ความสำคัญ"/><BarList rows={(data?.topMachines||[]).map(x=>({label:`${x.machine_no} ${x.machine_name}`,value:x.downtime_min}))} suffix="m"/></div></div>
    <div className="card"><CardTitle icon="report" title="ประวัติ PM" sub="ผลรวม ปกติ / แก้ไขแล้ว / พบปัญหา"/>{!data?.pmHistory?.length?<Empty title="ยังไม่มีประวัติ PM เดือนนี้"/>:<div className="table-wrap"><table className="table"><thead><tr><th>วันที่</th><th>เครื่อง</th><th>แผน</th><th>ผลรวม</th><th>เสร็จเมื่อ</th></tr></thead><tbody>{data.pmHistory.map(r=><tr key={r.id}><td>{formatThaiDate(r.due_date)}</td><td><b className="mono">{r.machine_no_snapshot}</b><br/>{r.machine_name_snapshot}</td><td>{r.plan_title_snapshot}</td><td><select className="select" style={{minHeight:34,padding:"0 8px",fontSize:11}} value={r.overall_result||""} onChange={e=>updatePmResult(r.id,e.target.value)}><option value="normal">ปกติ</option><option value="corrected">แก้ไขแล้ว</option><option value="issue">พบปัญหา</option></select></td><td>{r.completed_at?formatThaiDate(r.completed_at):"-"}</td></tr>)}</tbody></table></div>}</div>
  </div>
}
