import React, { useEffect, useMemo, useState } from "react";
import { addDaysISO, formatThaiDate, frequencyLabel, localDateISO, requireSupabase, rpc, startOfWeekISO, statusLabel } from "../../core.js";
import { Badge, CardTitle, Empty, ErrorState, Icon, Loading, Modal } from "../components/UI.jsx";

const DOW=["จ.","อ.","พ.","พฤ.","ศ.","ส.","อา."];
const MONTHS=["ม.ค.","ก.พ.","มี.ค.","เม.ย.","พ.ค.","มิ.ย.","ก.ค.","ส.ค.","ก.ย.","ต.ค.","พ.ย.","ธ.ค."];
const dateKey=d=>String(d||"").slice(0,10);
function groupByDate(rows){return rows.reduce((a,r)=>{(a[r.due_date]??=[]).push(r);return a},{})}
function weekDates(weekStart){return Array.from({length:7},(_,i)=>addDaysISO(weekStart,i))}
function defaultReading(item,existing){return {item_id:item.id,result:existing?.result||"",measured_value:existing?.measured_value??"",abnormal_detail:existing?.abnormal_detail||"",note:existing?.note||""}}

export default function PMModule({profile,go}){
  const admin=profile.role==="admin";
  const now=new Date(),today=localDateISO(now),currentYear=now.getFullYear();
  const [selectedYear,setSelectedYear]=useState(currentYear);
  const [view,setView]=useState("today"),[yearRows,setYearRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const [weekStart,setWeekStart]=useState(startOfWeekISO()),[selectedDay,setSelectedDay]=useState(today),[month,setMonth]=useState(now.getMonth()+1);
  const [runner,setRunner]=useState(null),[runnerLoading,setRunnerLoading]=useState(false),[items,setItems]=useState([]),[readings,setReadings]=useState({}),[runnerMsg,setRunnerMsg]=useState(""),[saving,setSaving]=useState(false);
  const [weekly,setWeekly]=useState([]),[weeklyLoading,setWeeklyLoading]=useState(false),[wkQuery,setWkQuery]=useState(""),[wkTask,setWkTask]=useState(null);

  async function loadYear(){setLoading(true);setError("");try{const sb=requireSupabase();const from=`${selectedYear}-01-01`,to=`${selectedYear}-12-31`;const {data,error}=await sb.from("pm_schedule").select("id,plan_id,department_id,machine_id,plan_title_snapshot,frequency_snapshot,machine_no_snapshot,machine_name_snapshot,std_minutes_snapshot,due_date,status,assigned_to,assignee_name_snapshot,started_at,completed_at,execution_note,overall_result").gte("due_date",from).lte("due_date",to).order("due_date");if(error)throw error;setYearRows(data||[])}catch(e){setError(e.message||"โหลดแผน PM ไม่สำเร็จ")}finally{setLoading(false)}}
  async function loadWeekly(){setWeeklyLoading(true);try{const sb=requireSupabase();const {data,error}=await sb.from("pm_weekly_tasks").select("id,week_start,day_of_week,department_id,machine_id,machine_no_snapshot,machine_name_snapshot,title,details,assigned_to,assignee_name_snapshot,status,note,sort_order,status_at").eq("week_start",weekStart).order("day_of_week").order("sort_order");if(error)throw error;setWeekly(data||[])}catch(e){setError(e.message||"โหลด TPM รายสัปดาห์ไม่สำเร็จ")}finally{setWeeklyLoading(false)}}
  useEffect(()=>{loadYear()},[selectedYear]);useEffect(()=>{if(view==="tpm")loadWeekly()},[view,weekStart]);
  useEffect(()=>{if(view==="week"&&!weekDates(weekStart).includes(selectedDay))setSelectedDay(weekStart)},[weekStart,view]);

  const weeks=weekDates(weekStart);const dayCount=d=>yearRows.filter(r=>r.due_date===d).length;
  const todayRows=yearRows.filter(r=>r.due_date===today);
  const weekRows=yearRows.filter(r=>weeks.includes(r.due_date));
  const monthRows=yearRows.filter(r=>Number(r.due_date?.slice(5,7))===month);
  const yearCounts=Array.from({length:12},(_,i)=>yearRows.filter(r=>Number(r.due_date?.slice(5,7))===i+1).length);

  async function openRunner(row){setRunner(row);setRunnerLoading(true);setRunnerMsg("");try{const sb=requireSupabase();if(row.status==="planned"){const {error}=await sb.from("pm_schedule").update({status:"in_progress",assigned_to:profile.id}).eq("id",row.id);if(error)throw error;row={...row,status:"in_progress",assigned_to:profile.id};setRunner(row)}const [ci,rd]=await Promise.all([sb.from("pm_checklist_items").select("id,plan_id,item_order,item_name,item_type,min_value,max_value,unit,is_active").eq("plan_id",row.plan_id).eq("is_active",true).order("item_order"),sb.from("pm_readings").select("item_id,result,measured_value,abnormal_detail,note").eq("schedule_id",row.id)]);if(ci.error)throw ci.error;if(rd.error)throw rd.error;setItems(ci.data||[]);const map=Object.fromEntries((ci.data||[]).map(i=>[i.id,defaultReading(i,(rd.data||[]).find(x=>x.item_id===i.id))]));setReadings(map)}catch(e){setRunnerMsg(e.message||"เปิดรายการตรวจไม่สำเร็จ")}finally{setRunnerLoading(false)}}
  function patchReading(item,k,v){setReadings(old=>{const r={...old[item.id],[k]:v};if(item.item_type==="measurement"&&k==="measured_value"&&v!==""){const n=Number(v);if(Number.isFinite(n)&&((item.min_value!=null&&n<Number(item.min_value))||(item.max_value!=null&&n>Number(item.max_value))))r.result="abnormal"}return {...old,[item.id]:r}})}
  function validateReadings(){for(const item of items){const r=readings[item.id]||{};if(!r.result)return `กรุณาเลือกผลตรวจ: ${item.item_name}`;if(item.item_type==="measurement"&&r.result!=="na"&&r.measured_value==="")return `กรุณากรอกค่าที่วัด: ${item.item_name}`;if(r.result==="abnormal"&&!String(r.abnormal_detail||"").trim())return `รายการผิดปกติต้องกรอกอาการหรือจุดที่พบ: ${item.item_name}`}return ""}
  async function saveChecklist(complete=false){const msg=validateReadings();if(msg){setRunnerMsg(msg);return}setSaving(true);setRunnerMsg("");try{const sb=requireSupabase();const rows=items.map(item=>{const r=readings[item.id];return {schedule_id:runner.id,item_id:item.id,result:r.result,measured_value:item.item_type==="measurement"&&r.measured_value!==""?Number(r.measured_value):null,abnormal_detail:r.result==="abnormal"?String(r.abnormal_detail).trim():null,note:String(r.note||"").trim()||null,inspector_id:profile.id}});const {error}=await sb.from("pm_readings").upsert(rows,{onConflict:"schedule_id,item_id"});if(error)throw error;if(complete){await rpc("complete_pm_schedule",{p_schedule_id:runner.id,p_execution_note:null});setRunnerMsg("บันทึกและปิดงาน PM เรียบร้อย");await loadYear();setTimeout(()=>setRunner(null),650)}else setRunnerMsg("บันทึกผลตรวจแล้ว") }catch(e){setRunnerMsg(e.message||"บันทึกผลตรวจไม่สำเร็จ")}finally{setSaving(false)}}
  async function updateWeeklyStatus(task,status,note=task.note||""){try{const sb=requireSupabase();const {error}=await sb.from("pm_weekly_tasks").update({status,note}).eq("id",task.id);if(error)throw error;setWkTask(null);await loadWeekly()}catch(e){setError(e.message||"อัปเดตงาน TPM ไม่สำเร็จ")}}
  function createRepairFromPM(){const abnormal=items.map(i=>({item:i,reading:readings[i.id]})).filter(x=>x.reading?.result==="abnormal");sessionStorage.setItem("mvr-repair-prefill",JSON.stringify({machine_id:runner.machine_id,symptom:abnormal.map(x=>`${x.item.item_name}: ${x.reading.abnormal_detail}`).join("\n"),problem_type:"PM Follow-up",cause:"พบจากการตรวจ PM",remark:`อ้างอิงงาน PM ${runner.plan_title_snapshot} วันที่ ${runner.due_date}`}));setRunner(null);go("repair")}

  function ScheduleCards({rows}){if(!rows.length)return <Empty title="ไม่มีงาน PM ในช่วงนี้" text="งานจะปรากฏเมื่อผู้ดูแลสร้างแผนและ Generate Schedule แล้ว"/>;const groups=groupByDate(rows);return <div className="stack">{Object.entries(groups).map(([date,list])=><div className="date-group" key={date}><div className="date-group-title"><span className="date-dot"/>{formatThaiDate(date,{weekday:"long"})}<span className="badge planned">{list.length} งาน</span></div><div className="list">{list.map(r=><div className="list-card" key={r.id}><div className="list-head"><div><div className="list-title"><span className="mono">{r.machine_no_snapshot}</span> · {r.machine_name_snapshot}</div><div className="list-sub">{r.plan_title_snapshot} · {frequencyLabel(r.frequency_snapshot)}</div></div><Badge value={r.status}/></div><div className="meta-row"><span>มาตรฐาน <b className="mono">{r.std_minutes_snapshot||0}</b> นาที</span>{r.assignee_name_snapshot&&<span>ผู้รับผิดชอบ {r.assignee_name_snapshot}</span>}{r.overall_result&&<Badge value={r.overall_result}/>}</div>{(()=>{const locked=!admin&&r.assigned_to&&r.assigned_to!==profile.id;const unavailable=r.status==="skipped"||locked;const label=r.status==="completed"?"ดูผลตรวจ":r.status==="skipped"?"งานถูกระบุว่าไม่ได้ทำ":locked?`มอบหมายให้ ${r.assignee_name_snapshot||"ช่างคนอื่น"}`:"เริ่มตรวจ";return <button className="btn soft small" style={{marginTop:10}} disabled={unavailable} onClick={()=>!unavailable&&openRunner(r)}><Icon name={r.status==="completed"?"list":"play"} size={15}/>{label}</button>})()}</div>)}</div></div>)}</div>}

  if(loading)return <Loading/>;if(error&&!yearRows.length)return <ErrorState message={error} onRetry={loadYear}/>;
  const wkFiltered=weekly.filter(t=>{const q=wkQuery.toLowerCase();return !q||`${t.title} ${t.machine_no_snapshot} ${t.machine_name_snapshot} ${t.assignee_name_snapshot}`.toLowerCase().includes(q)});const wkDone=weekly.filter(t=>t.status==="done").length,wkPct=weekly.length?Math.round(wkDone/weekly.length*100):0;
  return <div className="stack"><section className="hero"><div className="hero-kicker">PREVENTIVE & TOTAL PRODUCTIVE MAINTENANCE</div><h1>PM / TPM</h1><p>งานตามแผนเท่านั้น ช่างตรวจเช็กลิสต์และบันทึกผลโดยไม่แก้แผน</p><div className="hero-meta"><span className="hero-chip">ปี {selectedYear+543}</span><span className="hero-chip">{profile.departments?.dept_code||"ทุกแผนก"}</span></div></section>
    <div className="tabs">{[["today","วันนี้"],["week","รายสัปดาห์"],["month","รายเดือน"],["year","รายปี"],["tpm","TPM สัปดาห์"]].map(([k,l])=><button key={k} className={`tab ${view===k?"active":""}`} onClick={()=>{setView(k);if(k==="today"){setSelectedYear(currentYear);setMonth(now.getMonth()+1)}if(k==="week"){const ws=startOfWeekISO();setWeekStart(ws);setSelectedDay(today);setSelectedYear(currentYear)}}}>{l}</button>)}</div>
    {view==="today"&&<><div className="section-title"><div><h2>งานวันนี้</h2><p>{formatThaiDate(today,{weekday:"long"})}</p></div><span className="badge planned">{todayRows.length} งาน</span></div><ScheduleCards rows={todayRows}/></>}
    {view==="week"&&<><div className="card flat"><CardTitle icon="calendar" title="เลือกวันในสัปดาห์" sub="แต่ละวันแสดงจำนวนงาน และเมื่อเลือกจะแสดงเฉพาะวันนั้นเต็มหน้า"/><div className="field-grid cols-2" style={{marginBottom:12}}><div className="field"><label>สัปดาห์เริ่มวันจันทร์</label><input className="input" type="date" value={weekStart} onChange={e=>{const ws=startOfWeekISO(new Date(`${e.target.value}T12:00:00`));setWeekStart(ws);setSelectedYear(new Date(`${ws}T12:00:00`).getFullYear());setSelectedDay(ws)}}/></div><div className="field"><label>ปีแผน</label><select className="select" value={selectedYear} onChange={e=>setSelectedYear(Number(e.target.value))}>{[currentYear-1,currentYear,currentYear+1,currentYear+2].map(y=><option key={y} value={y}>{y+543}</option>)}</select></div></div><div className="day-tabs">{weeks.map((d,i)=><button key={d} className={`day-tab ${selectedDay===d?"active":""}`} onClick={()=>setSelectedDay(d)}><b>{DOW[i]}</b><span>{d.slice(8,10)} · {dayCount(d)}</span></button>)}</div></div><ScheduleCards rows={weekRows.filter(r=>r.due_date===selectedDay)}/></>}
    {view==="month"&&<><div className="card flat"><CardTitle icon="calendar" title="แผนรายเดือน" sub="ดูง่ายว่าเครื่องใดมีแผนวันไหน"/><div className="field-grid cols-2"><select className="select" value={month} onChange={e=>setMonth(Number(e.target.value))}>{MONTHS.map((m,i)=><option key={m} value={i+1}>{m} {selectedYear+543}</option>)}</select><select className="select" value={selectedYear} onChange={e=>setSelectedYear(Number(e.target.value))}>{[currentYear-1,currentYear,currentYear+1,currentYear+2].map(y=><option key={y} value={y}>{y+543}</option>)}</select></div></div><ScheduleCards rows={monthRows}/></>}
    {view==="year"&&<><div className="card flat"><CardTitle icon="calendar" title="ภาพรวมรายปี" sub="จำนวนรอบ PM/TPM ที่ถูก Generate ตามแผน"/><select className="select" value={selectedYear} onChange={e=>setSelectedYear(Number(e.target.value))}>{[currentYear-1,currentYear,currentYear+1,currentYear+2].map(y=><option key={y} value={y}>{y+543}</option>)}</select></div><div className="grid grid-3">{MONTHS.map((m,i)=><button key={m} className="card menu-card" onClick={()=>{setMonth(i+1);setView("month")}} style={{textAlign:"left",minHeight:120}}><div className="menu-card-top"><span className="menu-card-ico" style={{background:"linear-gradient(135deg,#6D5CE7,#8B7CF2)"}}><Icon name="calendar"/></span><span className="kpi-value" style={{fontSize:19}}>{yearCounts[i]}</span></div><div><h3>{m} {selectedYear+543}</h3><p>งานตามแผนทั้งหมด</p></div></button>)}</div></>}
    {view==="tpm"&&<><div className="card flat"><CardTitle icon="pm" title="TPM ประจำสัปดาห์" sub="ช่างแก้ได้เฉพาะสถานะปฏิบัติงานและหมายเหตุ"/><div className="field-grid cols-2"><div className="field"><label>สัปดาห์เริ่มวันที่</label><input type="date" className="input" value={weekStart} onChange={e=>setWeekStart(startOfWeekISO(new Date(`${e.target.value}T12:00:00`)))}/></div><div className="field"><label>ค้นหา</label><input className="input" value={wkQuery} onChange={e=>setWkQuery(e.target.value)} placeholder="งาน เครื่องจักร หรือช่าง"/></div></div><div style={{marginTop:14}}><div className="list-head"><b>ความคืบหน้าสัปดาห์นี้</b><span className="mono">{wkPct}%</span></div><div className="progress" style={{marginTop:7}}><span style={{width:`${wkPct}%`}}/></div></div></div>
      {weeklyLoading?<Loading/>:!wkFiltered.length?<Empty title="ยังไม่มีงาน TPM สัปดาห์นี้" text={admin?"ไปที่เมนูผู้ดูแลเพื่อวางแผนงาน TPM":"ผู้ดูแลยังไม่ได้วางแผนงาน TPM สำหรับสัปดาห์นี้"}/>:<div className="stack">{weeks.map((d,i)=>{const rows=wkFiltered.filter(t=>t.day_of_week===i+1);if(!rows.length)return null;return <div className="date-group" key={d}><div className="date-group-title"><span className="date-dot"/>{DOW[i]} {formatThaiDate(d)}</div><div className="list">{rows.map(t=><div className="list-card" key={t.id}><div className="list-head"><div><div className="list-title">{t.title}</div><div className="list-sub"><span className="mono">{t.machine_no_snapshot||"-"}</span> · {t.machine_name_snapshot||"ไม่ระบุเครื่อง"}</div></div><Badge value={t.status}/></div>{t.details&&<p style={{fontSize:12,margin:"8px 0 0"}}>{t.details}</p>}<div className="meta-row">{t.assignee_name_snapshot&&<span>ผู้รับผิดชอบ {t.assignee_name_snapshot}</span>}{t.note&&<span>หมายเหตุ {t.note}</span>}</div><button className="btn soft small" style={{marginTop:10}} onClick={()=>setWkTask(t)}>อัปเดตการปฏิบัติงาน</button></div>)}</div></div>})}</div>}
    </>}
    {runner&&<Modal title={`${runner.machine_no_snapshot} · ${runner.plan_title_snapshot}`} onClose={()=>setRunner(null)}>{runnerLoading?<Loading/>:<div className="stack">{runnerMsg&&<div className="card flat" style={{color:runnerMsg.includes("เรียบร้อย")||runnerMsg.includes("บันทึกผล")?"#08784C":"#B82E42"}}>{runnerMsg}</div>}{!items.length?<Empty title="แผนนี้ยังไม่มีรายการตรวจ" text="ผู้ดูแลต้องเพิ่ม Checklist Item ก่อนให้ช่างปฏิบัติงาน"/>:<div className="checklist">{items.map(item=>{const r=readings[item.id]||{};const n=Number(r.measured_value),out=item.item_type==="measurement"&&r.measured_value!==""&&Number.isFinite(n)&&((item.min_value!=null&&n<Number(item.min_value))||(item.max_value!=null&&n>Number(item.max_value)));return <div className={`check-item ${r.result==="abnormal"?"abnormal":""}`} key={item.id}><div className="check-name">{item.item_order}. {item.item_name}</div><div className="check-meta">{item.item_type==="measurement"?`ค่ามาตรฐาน ${item.min_value??"-"} – ${item.max_value??"-"} ${item.unit||""}`:"ตรวจสภาพทั่วไป"}</div>{item.item_type==="measurement"&&<div className="measure-row"><input className={`input mono ${out?"measure-danger":""}`} type="number" step="any" value={r.measured_value} onChange={e=>patchReading(item,"measured_value",e.target.value)} placeholder="ค่าที่วัด" disabled={runner.status==="completed"}/><span className="measure-unit">{item.unit||"unit"}</span></div>}<div className="result-grid">{[["normal","ปกติ"],["abnormal","ผิดปกติ"],["na","ไม่เกี่ยวข้อง"]].map(([v,l])=><button type="button" key={v} className={`result-btn ${v} ${r.result===v?"active":""}`} onClick={()=>runner.status!=="completed"&&patchReading(item,"result",v)}>{l}</button>)}</div>{r.result==="abnormal"&&<div className="field" style={{marginTop:9}}><label>อาการหรือจุดที่พบ <span className="req">*</span></label><textarea className="textarea" value={r.abnormal_detail} onChange={e=>patchReading(item,"abnormal_detail",e.target.value)} disabled={runner.status==="completed"} placeholder="ระบุความผิดปกติที่พบ"/></div>}<div className="field" style={{marginTop:9}}><label>หมายเหตุ</label><input className="input" value={r.note} onChange={e=>patchReading(item,"note",e.target.value)} disabled={runner.status==="completed"}/></div></div>})}</div>}{runner.status!=="completed"&&items.length>0&&<div className="form-actions"><button className="btn ghost" disabled={saving} onClick={()=>saveChecklist(false)}>บันทึกไว้ก่อน</button><button className="btn purple" disabled={saving} onClick={()=>saveChecklist(true)}>{saving?"กำลังบันทึก…":"บันทึกและจบงาน PM"}</button></div>}{runner.status==="completed"&&items.some(i=>readings[i.id]?.result==="abnormal")&&<button className="btn danger block" onClick={createRepairFromPM}><Icon name="repair" size={16}/>เปิดงานซ่อมติดตามจากรายการผิดปกติ</button>}</div>}</Modal>}
    {wkTask&&<Modal title="อัปเดตสถานะ TPM" onClose={()=>setWkTask(null)}><div className="stack"><div><b>{wkTask.title}</b><div className="muted" style={{fontSize:12}}>{wkTask.machine_no_snapshot} · {wkTask.machine_name_snapshot}</div></div><div className="field"><label>สถานะปฏิบัติงาน</label><select className="select" value={wkTask.status} onChange={e=>setWkTask(t=>({...t,status:e.target.value}))}><option value="planned">วางแผนไว้</option><option value="in_progress">กำลังทำ</option><option value="done">เสร็จ</option><option value="skipped">ไม่ได้ทำ</option></select></div><div className="field"><label>หมายเหตุ</label><textarea className="textarea" value={wkTask.note||""} onChange={e=>setWkTask(t=>({...t,note:e.target.value}))}/></div><button className="btn primary block" onClick={()=>updateWeeklyStatus(wkTask,wkTask.status,wkTask.note)}>บันทึกสถานะ</button></div></Modal>}
  </div>
}
